/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Maria' at '5/21/16 4:03 PM' with Gradle 2.6
 *
 * @author Maria, @date 5/21/16 4:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
